### ISSUE TITLE
[Feature Request] Claude Instant 対応

### ISSUE THREAD

**Issue by maekawataiki** [aws-samples/jp-rag-sample#13]
RAG においては Claude Instant でも十分要約と出典のリストが可能なためレイテンシとコストの低い Claude Instant のサポートもあると良い。

**Comment by ysekiy** [comment]
## 料金の差
instant のほうが安い
https://aws.amazon.com/jp/bedrock/pricing/?nc1=h_ls
![Screenshot 2023-10-09 at 11 32 30](https://github.com/aws-samples/jp-rag-sample/assets/84328663/69c8525b-de68-47bb-b569-13b4d4cf7628)

## レイテンシー
low-latency との触れ込みがある
![Screenshot 2023-10-09 at 11 34 09](https://github.com/aws-samples/jp-rag-sample/assets/84328663/698d289d-c9a0-42b7-bb17-efe7bc8c56c0)

たしかに、
[https://github.com/ysekiy/jp-rag-sample/blob/d32c6c034304f8c20933b6896ef51f60aef08[…]y/backend/api/fargate/src/langchain/app/chain/claude_bedrock.py](https://github.com/ysekiy/jp-rag-sample/blob/d32c6c034304f8c20933b6896ef51f60aef08012/amplify/backend/api/fargate/src/langchain/app/chain/claude_bedrock.py#L13)

を変えて、defaultをinstantにしておくほうが良さそうですね。

**Comment by ysekiy** [comment]
https://github.com/aws-samples/jp-rag-sample/pull/16

dry-run&approve おねしゃす。
