### ISSUE TITLE
Workshop Studio のコンテンツにも対応できるように旧バージョン(SageMaker Endpoint on Rinna) のバージョンもタグ付けしていただきたい

### ISSUE THREAD

**Issue by satokod777** [aws-samples/jp-rag-sample#14]
Jumpstart 対応、 Bedrock 対応により、以下のハンズオンの手順やデプロイされるインスタンスタイプが変更されるため、既存の資料でハンズオンを実施できるよう旧バージョンのコミットについてもタグ付けしていただけますと幸いです。

https://catalog.us-east-1.prod.workshops.aws/workshops/6708bce5-6aa3-4acb-89f7-85c39c006c8c/en-US/01-introduction

**Comment by ysekiy** [comment]
相談ありがとうございます。根本課題はinstance typeの変更ということと理解しました。

一晩寝て考えてみたんですが、下記ドキュメントを見ると、
1. tag付けによる旧バージョン利用
2. jumpstart実装のinstance type固定
の２つありそうですね。

https://sagemaker.readthedocs.io/en/stable/api/inference/model.html
![Screenshot 2023-10-09 at 11 16 05](https://github.com/aws-samples/jp-rag-sample/assets/84328663/16411662-ba00-4af6-b943-b2640a4de8b9)

旧バージョンをv0.0.x系として活かすのもありますが、限られた開発リソースの中でスケールする方法を考えた場合、新しい方を良くする方がいいと思うので、v0.1.x系(defaultがrinna), v0.2.x系(defaultがbedrock) の両方に

https://github.com/aws-samples/jp-rag-sample/blob/main/llm/deploy_llm.sh
```
model = JumpStartModel(
    model_id="huggingface-llm-rinna-3-6b-instruction-ppo-bf16",
    model_version="v1.2.0",
    instance_type="ml.g4dn.xlarge"  # new line
)
```

といったinstance type固定化のコミットを打ち込むのどうでしょう(私未検証ですが。。)
そうすれば、https://github.com/aws-samples/jp-rag-sample/issues/15 のコスト問題も解消され、document updateも少なくて済むように思います。

**Comment by ysekiy** [comment]
@satokod777 問題なさそうであれば、PR立ててくださいませ。

## default bedrock ver.
[v0.2.0](https://github.com/aws-samples/jp-rag-sample/releases/tag/v0.2.0) → v0.2.1(instance type 固定化)

## default rinna ver.
[v0.1.2](https://github.com/aws-samples/jp-rag-sample/releases/tag/v0.1.2) → v0.1.3(instance type 固定化)

としましょうか。

**Comment by satokod777** [comment]
ご対応ありがとうございます。そのような方針でお願いできれば幸いです。

**Comment by ysekiy** [comment]
## 提案
旧バージョン v0.1系 update停止, v0.1.x-latest branch 廃止

## 理由
リソース不足。ここ数日のv0.2系のhotfixですらv0.1が追従できていない。
v0.1.x 系があるのって、workshop studio など aws derivery なコンテンツへのサポートだったはずでで、手順書であればどうしても固定化したい場合 `git clone <this-repo> -b <commit-id>` で良い気がする。

あと、 llm=rinnaのように変数を変えた手順書をつくれば良い話。
いうても、`amplify/backend/api/fargate/src/docker-compose.yml` の環境をいじる１工程

手順書、書くとすると
```
npm -g i c9  # install c9 extention
c9 amplify/backend/api/fargate/src/docker-compose.yml  # open in c9
# edit
# save
```
ぐらい。そこまで面倒ではない。

新しい機能はmain(=v0.2 latest) に追加していく、v0.2系の updateをかけるためだけでも、dry-run に人を当ててる。
v0.1 に hotfix にまでリソースなく、人を当てられない。
課題に対して、手段がtoo much な気がする。

## request for action
- 各お手持ちの資料のupdate(due date: 2023/10/31)
- member
  - @maekawataiki 
  - @tanimiya 
  - @satokod777 
  - suzuki-san (https://github.com/aws-samples/jp-rag-sample/issues/10)

**Comment by tanimiya** [comment]
0.2系でもDocker Compose編集すればRinna使えると理解しているのでバージョンまとめてしまうことは賛成です。
Just Ideaですが、llmの切り替えもシェルかなんかで処理してしまうのはどうかなと。
docker-compose.yamlのtemplateを2種類用意しておいてシェルでCopyするやつを切り替えるとか。
2つ用意するのも大変という話であればShell側でもう少しどうにかできれば良いかなと。

**Comment by ysekiy** [comment]
@tanimiya 

コメントありがとうございます。下記手順の簡素化って感じですかね。すごく良さそうですね。 @satokod777 にも現場感をコメントほしいところ。

```
npm -g i c9  # install c9 extention
c9 amplify/backend/api/fargate/src/docker-compose.yml  # open in c9
# edit
# save
```

**Comment by satokod777** [comment]
連絡遅くなりすみませんmm

バージョンが複数存在することで開発速度が落ちているのであれば、一つにまとめて、必要に応じて Shell で切り替えることは賛成です。ハンズオン等で動作実績のある指定したバージョンを利用したい場合は、コミット ID 固定して Clone してあげれば良いと思いますし、バージョンを統合することによるリスク、デメリットは大きく存在しないかなと思います。
