### ISSUE TITLE
LangChain service doesn't work

### ISSUE THREAD

**Issue by suzukyz** [aws-samples/jp-rag-sample#28]
## Issue Report

LangChain service on ECS/Fargete doesn't work when we use Rinna.
Because LangChain module path was changed.

## Expected Behavior

LangChain service and SPA work.

## Actual Behavior

LangChain service works incorrectly. Also SPA doesn't be loaded.

## Steps to Reproduce the Issue

Deploy with Rinna.

## How to fix

In `jp-rag-sample/amplify/backend/api/fargate/src/langchain/app/chain/rinna.py`
### Current source code:
```
L7: from langchain import SagemakerEndpoint
```
### Fixed source code:
```
L7: from langchain.llm import SagemakerEndpoint
```

### Related issue:
- https://stackoverflow.com/questions/77191535/langchain-root-module-no-longer-supported

### Related docs:
- https://python.langchain.com/docs/integrations/llms/sagemaker#example

**Comment by ysekiy** [comment]
https://github.com/aws-samples/jp-rag-sample/pull/29
