### ISSUE TITLE
ai の出力に改行コードが入っている場合に反映

### ISSUE THREAD

**Issue by ysekiy** [aws-samples/jp-rag-sample#35]
再現方法については追って追記

**Comment by raggbal** [comment]
[現状]
AI回答の部分の改行がされていないので、若干見づらく感じます。

<img width="731" alt="image" src="https://github.com/aws-samples/jp-rag-sample/assets/11311373/cbe1fdbc-6b6d-46ec-8dac-ca3e6dc97973">


[理想]
apiのレスポンスに \n が入っているため、それを<br/>に変換することで見やすくして欲しいです。

<img width="716" alt="image" src="https://github.com/aws-samples/jp-rag-sample/assets/11311373/4d8b696d-14fb-49d9-be46-db46250586e4">

**Comment by ysekiy** [comment]
v0.3.0 includes this
