### ISSUE TITLE
[feature request] API Gatewayへのオーソライザ設定追加

### ISSUE THREAD

**Issue by izuwataq** [aws-samples/jp-rag-sample#41]
## Issue Report

API Gatewayが現状オーソライザ設定されていないので認証なしで呼び出せてしまい、なおかつHTTP APIなのでWAFアタッチやリソースベースポリシーによるIP制限もできない。

## Expected Behavior

API Gatewayにオーソライザの設定がされ、httpヘッダに有効なJWTトークンが含まれていない場合は認証エラーとなるようにする。

## Actual Behavior

認証なしでAPIを呼び出せてしまう。

## Steps to Reproduce the Issue

curlコマンド等でAPI GatewayのURLを直接呼び出すと、認証なしでも結果を取得できる。

**Comment by ysekiy** [comment]
merged
