### ISSUE TITLE
[Proposal] CDK Migration

### ISSUE THREAD

**Issue by maekawataiki** [aws-samples/jp-rag-sample#47]
## Proposed Change

- 現状 Amplify + CloudFormation + スクリプトで管理しているリソースを CDK に移行

## Problem

- Amplify 管理対象外のリソース（Kendra、SageMaker等）をデプロイするために Role を用意したり手順が煩雑になっている。
- Amplify の制約
  - https://github.com/aws-amplify/amplify-category-api/issues/696
  - https://github.com/aws-amplify/amplify-category-api/issues/1715
  - https://github.com/aws-amplify/amplify-cli/issues/8120
    - Related: #36

## Expected Outcome

- リソースの管理を CDK に移行することで `cdk:deploy` だけでデプロイできるようにする。
- CDK を利用することでリソースの設定をより柔軟に変更できるようにする。

## Consideration

- 破壊的な変更になるためメジャーバージョンを変える。

**Comment by ysekiy** [comment]
merged
