### ISSUE TITLE
LambdaのNode.js14サポート終了に伴い、スタックの作成が失敗する

### ISSUE THREAD

**Issue by kazuki306** [aws-samples/jp-rag-sample#53]
## Issue Report
`amplify/backend/api/fargate/src/docker-compose.yml`内で定義されている以下３つのLambda関数のRuntimeが"nodejs14.x"となっており、それが原因でスタックの作成に失敗したとエラーが表示されてしまう
- AwaiterMyProviderframeworkonEventB703D418
- AwaiterMyProviderframeworkisComplete18658065
- AwaiterMyProviderframeworkonTimeoutCC4166A7

<img width="968" alt="スクリーンショット 2024-03-05 1 24 10" src="https://github.com/aws-samples/jp-rag-sample/assets/68455179/cea6a9d2-4981-4cec-b31d-ef885b89ea05">

## Expected Behavior
スタックが正常にデプロイされること

**Comment by ysekiy** [comment]
v0.3.0 includes this
